const agentsActionsTypes = {
    GET_USER_AGENTS_REQUEST: 'GET_USER_AGENTS_REQUEST',
    GET_USER_AGENTS_SUCCESS: 'GET_USER_AGENTS_SUCCESS',
    GET_USER_AGENTS_FAILURE: 'GET_USER_AGENTS_FAILURE',

    GET_EVENT_AGENTS_REQUEST: 'GET_EVENT_AGENTS_REQUEST',
    GET_EVENT_AGENTS_SUCCESS: 'GET_EVENT_AGENTS_SUCCESS',
    GET_EVENT_AGENTS_FAILURE: 'GET_EVENT_AGENTS_FAILURE',

    CREATE_AGENT_REQUEST: 'CREATE_AGENT_REQUEST',
    CREATE_AGENT_SUCCESS: 'CREATE_AGENT_SUCCESS',
    CREATE_AGENT_FAILURE: 'CREATE_AGENT_FAILURE'
};

export default agentsActionsTypes;