export const eventsActionsTypes = {
    GET_CATEGORYS_REQUEST: 'GET_CATEGORYS_REQUEST',
    GET_CATEGORYS_SUCCESS: 'GET_CATEGORYS_SUCCESS',
    GET_CATEGORYS_ERROR: 'GET_CATEGORYS_ERROR',

    GET_EVENTS_REQUEST: 'GET_EVENTS_REQUEST',
    GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
    GET_EVENTS_ERROR: 'GET_EVENTS_ERROR',

    CREATE_EVENT_REQUEST: 'CREATE_EVENT_REQUEST',
    CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
    CREATE_EVENT_ERROR: 'CREATE_EVENT_ERROR',

    GET_EVENT_REQUEST: 'GET_EVENT_REQUEST',
    GET_EVENT_SUCCESS: 'GET_EVENT_SUCCESS',
    GET_EVENT_ERROR: 'GET_EVENT_ERROR'
}