export const eventsActionsTypes = {
    GET_CATEGORYS_REQUEST: 'GET_CATEGORYS_REQUEST',
    GET_CATEGORYS_SUCCESS: 'GET_CATEGORYS_SUCCESS',
    GET_CATEGORYS_ERROR: 'GET_CATEGORYS_ERROR',

    GET_EVENTS_REQUEST: 'GET_EVENTS_REQUEST',
    GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
    GET_EVENTS_ERROR: 'GET_EVENTS_ERROR',

    GET_UPCOMING_EVENTS_REQUEST: 'GET_UPCOMING_EVENTS_REQUEST',
    GET_UPCOMING_EVENTS_SUCCESS: 'GET_UPCOMING_EVENTS_SUCCESS',
    GET_UPCOMING_EVENTS_ERROR: 'GET_UPCOMING_EVENTS_ERROR',

    CREATE_EVENT_REQUEST: 'CREATE_EVENT_REQUEST',
    CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
    CREATE_EVENT_ERROR: 'CREATE_EVENT_ERROR',

    GET_EVENT_REQUEST: 'GET_EVENT_REQUEST',
    GET_EVENT_SUCCESS: 'GET_EVENT_SUCCESS',
    GET_EVENT_ERROR: 'GET_EVENT_ERROR',

    DESTROY_EVENTS_STATE: 'DESTROY_EVENTS_STATE',

    UPDATE_EVENT_REQUEST: 'UPDATE_EVENT_REQUEST',
    UPDATE_EVENT_SUCCESS: 'UPDATE_EVENT_SUCCESS',
    UPDATE_EVENT_ERROR: 'UPDATE_EVENT_ERROR',
    
    DELETE_EVENT_REQUEST: 'DELETE_EVENT_REQUEST',
    DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
    DELETE_EVENT_ERROR: 'DELETE_EVENT_ERROR',
}