const ticketsActionsTypes = {
    GET_TICKETS_REQUEST: 'GET_TICKETS_REQUEST',
    GET_TICKETS_SUCCESS: 'GET_TICKETS_SUCCESS',
    GET_TICKETS_ERROR: 'GET_TICKETS_ERROR',

    CREATE_TICKET_REQUEST: 'CREATE_TICKET_REQUEST',
    CREATE_TICKET_SUCCESS: 'CREATE_TICKET_SUCCESS',
    CREATE_TICKET_ERROR: 'CREATE_TICKET_ERROR',

    PURCHASE_TICKET_START: 'PURCHASE_TICKET_START',
    PURCHASE_TICKET_SUCCESS: 'PURCHASE_TICKET_SUCCESS',
    PURCHASE_TICKET_ERROR: 'PURCHASE_TICKET_ERROR',

    GET_USER_TICKETS_START: 'GET_USER_TICKETS_START',
    GET_USER_TICKETS_SUCCESS: 'GET_USER_TICKETS_SUCCESS',
    GET_USER_TICKETS_ERROR: 'GET_USER_TICKETS_ERROR',

    GET_PURCHASES_REQUEST: 'GET_PURCHASES_REQUEST',
    GET_PURCHASES_SUCCESS: 'GET_PURCHASES_SUCCESS',
    GET_PURCHASES_ERROR: 'GET_PURCHASES_ERROR',
};

export default ticketsActionsTypes;